name: Lint with Postman CLI

on: 
  push:
  workflow_dispatch:

jobs:
  automated-api-linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API linting
        run: |
          # Lint your API using Postman CLI
          postman api lint --integration-id 138662
